### ISSUE TITLE
Decryption 

### ISSUE THREAD

**Issue by everight** [v4resk/BreachCheck#2]
Hey, I want to know what type of hash encryption is used on yhe hash_password and if anyone know how to decrypt it.

**Comment by v4resk** [comment]
Hello, this tools print SHA1 hashes. I have updated it to print the hash algorithm.
You may use Hashcat to attempt cracking a SHA1 hash: [infiltr8 - Offline - Password Cracking](https://red.infiltr8.io/redteam/credentials/passwd/brute-force/offline-password-cracking)
